Commands:
  windows:
    shell: "powershell"
    Cpu: "[PSCustomObject]@{CPU_Usage_Percent = (Get-CimInstance Win32_Processor).LoadPercentage} | ConvertTo-Json -Compress"
    Ram: "Get-CimInstance Win32_OperatingSystem | ForEach-Object { [PSCustomObject]@{RAM_Usage_Percent = (($_.TotalVisibleMemorySize - $_.FreePhysicalMemory) / $_.TotalVisibleMemorySize) * 100} } | ConvertTo-Json -Compress"
    Process:  |
                Get-Process | 
                    Sort-Object CPU -Descending | 
                    Select-Object -First 15 | 
                    Select-Object Name, 
                                  Id, 
                                  @{Name="CPU_Percent"; Expression={if ($_.CPU) { $_.CPU } else { 0 }}}, 
                                  @{Name="RAM"; Expression={$_.WorkingSet}} | 
                    ConvertTo-Json
    #se fuerza a ser una lista para no tener que hacer un caso para windows y otro para linux
    Storage: |
              $discos = @( Get-CimInstance Win32_LogicalDisk -Filter "DriveType=3" ) |
              Select-Object DeviceID, 
              Size, 
              @{Name="Used"; Expression={$_.Size - $_.FreeSpace}}, 
              @{Name="Free"; Expression={$_.FreeSpace}}

                        ConvertTo-Json -InputObject @(,$discos)        
                    
  linux:
    sell: "bash"
    Cpu: top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print "{\"CPU_Usage_Percent\":" 100 - $1 "}"}'
    Ram: free | awk 'NR==2{print "{\"RAM_Usage_Percent\":" ($3/$2)*100 "}"}'
    Process: ps -eo comm,pid,%cpu,%mem --sort=-%cpu | head -n 16 | awk 'NR>1 {print "{\"Name\":\""$1"\",\"Id\":"$2",\"CPU_Percent\":"$3",\"RAM\":"$4"}"}' | awk 'BEGIN{print "["} {print $0 (NR==1?"":",")} END{print "]"}' | sed 's/},/}/' | sed '$s/},/}/'
    Storage: df -B1 --output=source,size,used,avail / | tail -n 1 | awk '{print "{\"DeviceID\":\""$1"\",\"Size\":"$2",\"Used\":"$3",\"Free\":"$4"}"}'




ConditionsToEvaluete:
  CpuMax: 90
  RamMax: 80
  FreeStorageMin: 20


critical_files:
  - ".env"
  - "config.yaml"
  - "settings.json"

default_format: "json"
  
default_output: "./reports/"
  